name: Build ComfyUI Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build \
          --progress=plain \
          --no-cache \
          -t comfyui-runpod \
          . 2>&1 | tee build.log
        
        # Vérifier si le build a réussi
        if [ $? -ne 0 ]; then
          echo "Build failed, saving logs"
          tail -100 build.log > failure.log
          cat failure.log
          exit 1
        fi

    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: docker-build-logs
        path: build.log
